spring:
  application:
    name: fraud-transaction-adapter
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: fraud-transaction-adapter
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

adapter:
  kafka:
    inbound-topic: MQ-CREDIT-TXNS
    outbound-topic: MQ-CREDIT-REPLIES
  credit-score:
    base-url: ${CREDIT_SCORE_BASE_URL:https://localhost:9095}
    score-path: /credit/score
